services:
  suendenbock_app:
    image: ${DOCKER_REGISTRY-}suendenbockapp
    build:
      context: .
      dockerfile: Suendenbock_App/Dockerfile
    volumes:                                     
      - ./uploads:/app/wwwroot/images            
